<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>pf-task</title>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<?
echo Phalcon\Tag::stylesheetLink('css/main.css');
if ($this->view->getVar('jsEnabled')) {
	echo Phalcon\Tag::javascriptInclude('https://code.jquery.com/jquery.js', false);
	echo Phalcon\Tag::javascriptInclude('js/main.js');
}
?>
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<nav class="navbar">
<?=$this->partial('partials/navbar')?>
		</nav>
		<section>
<?=$this->getContent() ?>
		</section>
	</body>
</html>